import React from 'react';
import { SignIn } from '@/components/Auth';

export const metadata = {
  title: 'Sign In - Authorization and Authentication App',
  description: 'Generated by create next app',
};

const Page = () => {
  return (
    <>
      <SignIn />
    </>
  );
};

export default Page;
