import SignIn from '@/components/Auth/SignIn';
import React from 'react';


export const metadata = {
  title: 'Sign In - Authorization and Authentication App',
  description: 'Generated by create next app',
};

const Page = () => {
  return (
    <>
      <SignIn />
    </>
  );
};

export default Page;
