import UserDash from '@/components/Dashboard/User';
import React from 'react';

export const metadata = {
  title: 'Dashboard - Authorization and Authentication App',
  description: 'Generated by create next app',
};

const Page = () => {
  return (
    <>
      <UserDash />
    </>
  );
};

export default Page;
