import AdminDash from '@/components/Dashboard/Admin';
import React from 'react';

export const metadata = {
  title: 'Admin Dashboard - Authorization and Authentication App',
  description: 'Generated by create next app',
};

const Page = () => {
  return (
    <>
      <AdminDash />
    </>
  );
};

export default Page;
