import React from 'react';
import { SignUp } from '@/components/Auth';

export const metadata = {
  title: 'Sign Up - Authorization and Authentication App',
  description: 'Generated by create next app',
};

const Page = () => {
  return (
    <>
      <SignUp />
    </>
  );
};

export default Page;
