import React, { useEffect, useState } from 'react';

import '../styles/globals.css';
import Head from 'next/head';
import { SessionProvider } from 'next-auth/react';
import MainLayout from '@/components/Layout/Layout';

export default function App({
  Component,
  pageProps: { session, ...pageProps },
}) {
  const [showing, setShowing] = useState(false);

  useEffect(() => {
    setShowing(true);
  }, []);

  if (!showing) {
    return null;
  }

  if (typeof window === 'undefined') {
    return <></>;
  } else {
    return (
      <>
        <Head>
          <title>Jikmunn Next Auth</title>
          <meta name="description" content="Generated by create next app" />
          <meta name="viewport" content="width=device-width, initial-scale=1" />
          <link rel="icon" href="/favicon.ico" />
        </Head>
        <SessionProvider
          session={session}
          // basePath="/user/api/auth"
        >
          <MainLayout>
            <Component {...pageProps} />
          </MainLayout>
        </SessionProvider>
      </>
    );
  }
}
